'use client';
import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import InfoBlock from '@/components/block';
import {useEffect, useState} from 'react';

const BASE_URL = 'http://localhost:3000/api'

export default function Home() {
  const [diaAtual, setDiaAtual] = useState<number>();

  const today = new Date();
  const day = today.getDate();
  const month = today.getMonth() + 1; // Os meses são baseados em zero
  const year = today.getFullYear();

  async function carregarDia(dia: number, mes: number) {
    const resp = await fetch(`${BASE_URL}/infodias/${mes}/${dia}`);
    const json = await resp.json();
    setDiaAtual(json.info);
    console.log(`dia atual: ${json.info}`);
  }  

  useEffect(() => {
    carregarDia(day, month)
  }, [day])

  function renderizarDia(dia: any) {
    if (dia.length > 0) {
    return (
      dia.map((item: any) => (
        <InfoBlock group={item.group} title={item.title} amount={item.amount} />
      ))
    );
    }
  }  

  return (
    <>
      <Head>
        <title>Santa Rita</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className={styles.header}>
          <p>Fertirrigação do dia {day}/{month}/{year}</p>
        </div>
        <div className={styles.blocksDiv}>
          {diaAtual && renderizarDia(diaAtual)}
        </div>
      </div>
    </>
  )
}
